config/routes.rb
Multicaja::Application.routes.draw do
  
  root 'movements#index'
  resources :debit_movements
  resources :credit_movements
  resources :movements

  

end

app/models/credit_movement.rb
# encoding: utf-8
class CreditMovement < Movement
  
  def to_s
    return "Crédito"    # TODO el acento!!
  end
  
end

app/models/debit_movement.rb
# encoding: utf-8
class DebitMovement < Movement
  
  def to_s
    return "Débito"
  end
  
end

app/models/movement.rb
class Movement < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/credit_movements_controller.rb
class CreditMovementsController < MovementsController
  
  def new
     @credit_movement = CreditMovement.new
  end
  
  def create
    @credit_movement = CreditMovement.new(movement_params)

    respond_to do |format|
      if @credit_movement.save
        format.html { redirect_to @credit_movement, notice: 'Credit Movement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @credit_movement }
      else
        format.html { render action: 'new' }
        format.json { render json: @credit_movement.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def movement_params
    params.require(:credit_movement).permit(:amount, :moment, :short_description)
  end
  
end

app/controllers/debit_movements_controller.rb
class DebitMovementsController < MovementsController
  
  def new
     @debit_movement = DebitMovement.new
  end

  def create
    @debit_movement = DebitMovement.new(movement_params)

    respond_to do |format|
      if @debit_movement.save
        format.html { redirect_to @debit_movement, notice: 'Debit Movement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @debit_movement }
      else
        format.html { render action: 'new' }
        format.json { render json: @debit_movement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  #def show
  #end
  
  def movement_params
    params.require(:debit_movement).permit(:amount, :moment, :short_description)
  end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]

  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.all
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements
  # POST /movements.json
  def create
    # @movement = Movement.new(movement_params)
# 
    # respond_to do |format|
      # if @movement.save
        # format.html { redirect_to @movement, notice: 'Movement was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @movement }
      # else
        # format.html { render action: 'new' }
        # format.json { render json: @movement.errors, status: :unprocessable_entity }
      # end
    # end
  end

  # PATCH/PUT /movements/1
  # PATCH/PUT /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # TODO hacerlo abstracto
    def movement_params
    #  params.require(:movement).permit(:amount, :moment, :movementable_id, :movementable_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_movement_helper.rb
module CreditMovementHelper
end

app/helpers/debit_movements_helper.rb
module DebitMovementsHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/credit_movements/_form.html.erb
<%= form_for(@credit_movement) do |f| %>
  <% if @credit_movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @credit_movement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :moment %><br>
    <%= f.datetime_select :moment %>
  </div>
    <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description, :cols=>"50", :rows=>"10"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_movements/index.html.erb
<h1>New Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_movement %> |
<%= link_to 'Back', movements_path %>

app/views/credit_movements/new.html.erb
<h1>New Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_movement %> |
<%= link_to 'Back', movements_path %>

app/views/debit_movements/_form.html.erb
<%= form_for(@debit_movement) do |f| %>
  <% if @debit_movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debit_movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @debit_movement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :moment %><br>
    <%= f.datetime_select :moment %>
  </div>
    <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description, :cols=>"50", :rows=>"10"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debit_movements/create.html.erb
<h1>DebitMovements#create</h1>
<p>Find me in app/views/debit_movements/create.html.erb</p>

app/views/debit_movements/destroy.html.erb
<h1>DebitMovements#destroy</h1>
<p>Find me in app/views/debit_movements/destroy.html.erb</p>

app/views/debit_movements/edit.html.erb
<h1>Editing Debit</h1>

<%= render 'form' %>

<%= link_to 'Show', @debit_movement %> |
<%= link_to 'Back', movements_path %>

app/views/debit_movements/index.html.erb
<h1>New Debit</h1>

<%= render 'form' %>

<%= link_to 'Show', @debit_movement %> |
<%= link_to 'Back', movements_path %>

app/views/debit_movements/new.html.erb
<h1>New Debit</h1>

<%= render 'form' %>

<%= link_to 'Show', @debit_movement %> |
<%= link_to 'Back', movements_path %>

app/views/debit_movements/update.html.erb
<h1>DebitMovements#update</h1>
<p>Find me in app/views/debit_movements/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multicaja</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movements/_form.html.erb
<%= form_for(@movement) do |f| %>
  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @movement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :moment %><br>
    <%= f.datetime_select :moment %>
  </div>
  <!--
  <div class="field">
    <%= f.label :movementable_id %><br>
    <%= f.number_field :movementable_id %>
  </div>
  <div class="field">
    <%= f.label :movementable_type %><br>
    <%= f.text_field :movementable_type %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing movement</h1>

<%= render 'form' %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<h1>Listing movements</h1>

<!-- Agregado de estilo para esta tabla -->
<style>
	table {
		border-collapse: collapse;
	}
	table, td, th {
		border: 1px solid green;
	}
	th {
		background-color: green;
		color: white;
	}
	td {
		padding:10px;
	}
</style>

<table>
	<thead>
		<tr>
			<th>Amount</th>
			<th>Moment</th>
			<th>Type</th>
			<th>Short Description</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @movements.each do |movement| %>
		<tr>
			<td><%= movement.amount %></td>
			<td><%= movement.moment %></td>
			<td><%= movement.to_s %></td>
			<td><%= movement.short_description %></td>

			<% if false %>
			<%-# Alta grasada para comentar un bloque! -%>
			<td><%= movement.movementable_id %></td>
			<td><%= movement.movementable_type %></td>

			<td><%= link_to 'Show', movement %></td>
			<td><%= link_to 'Edit', edit_movement_path(movement) %></td>
			<td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% end %>
			<td><%= link_to 'Edit', edit_movement_path(movement) %></td>

		</tr>
		<% end %>
	</tbody>
</table>

<br />
<%= link_to 'New Debit Movement', new_debit_movement_path %>
<br />
<%= link_to 'New Credit Movement', new_credit_movement_path %>

app/views/movements/new.html.erb
<h1>New movement</h1>

<%= render 'form' %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @movement.amount %>
</p>

<p>
  <strong>Moment:</strong>
  <%= @movement.moment %>
</p>

<p>
  <strong>Movementable:</strong>
  <%= @movement.movementable_id %>
</p>

<p>
  <strong>Movementable type:</strong>
  <%= @movement.movementable_type %>
</p>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>